### ISSUE TITLE
hey what pacakges do i need my zphisher.sh not working and lolcx also doesnt 

### ISSUE THREAD

**Issue by FishingPonds** [htr-tech/zphisher#638] opened 2022-11-08 09:08 UTC
### Describe the bug

hey what pacakges do i need my zphisher.sh not working and lolcx also doesnt

**Comment by htr-tech** [comment] 2022-11-08 09:39
duplicate of #639

Please share your comments there

**Closed by htr-tech** 2022-11-08 09:39 UTC
Labels: bug
